### ISSUE TITLE
Column sorting in open/import/cache dialog

### ISSUE THREAD

**Issue by djhoese** [ssec/sift#118]
In GitLab by @djhoese on Nov 2, 2015, 18:20

It would be really cool to have sortable columns when opening files or browsing the cache by having columns for various metadata (instrument, time step, data type, etc).

**Comment by gerritholl** [comment]
This would seem to be already implemented.  However, sorting by a numeric column such as `repeat_cycle_in_day` for FCI sorts it as if it's a string: 1, 10, 11, ..., 19, 2, 20, ...  It does strip the leading zeroes present in the filename, so evidently it has been interpreted as a number somewhere along the processing chain.

**Comment by djhoese** [comment]
@gerritholl could you file a separate issue and include a screenshot of the window and the incorrect sorting? I think you're right this is implemented. I'll close this and we can consider the sorting problem a separate issue.
