### ISSUE TITLE
Incorrect geolocation for ABI L1B RadC (CONUS) data

### ISSUE THREAD

**Issue by gerritholl** [ssec/sift#252]
When loading `OR_ABI-L1b-RadC-M6C03_G16_s20191231841244_e20191231844017_c20191231844066.nc` using `sift`, the geolocation is wrong:

![sift_screenshot](https://user-images.githubusercontent.com/500246/68144314-b2d18000-ff33-11e9-995a-993502b57930.png)

We can clearly see from the coastlines how Baja California is shifted to South Texas.

When I load the same using `satpy`, it is correct:

![C03](https://user-images.githubusercontent.com/500246/68144575-486d0f80-ff34-11e9-85b6-c9e9d4919cca.jpg)

I obtained the ABI CONUS data from using `aws s3 sync s3://noaa-goes16/ABI-L1b-RadC/2019/123/ --no-sign-request /path/to/local/directory`.  I have installed from the latest Github, in fact from https://github.com/katherinekolman/sift/commit/2f36231ae3688ad8b3c934bfbd6f657b17fa2ab4 to avoid some of the installation-related issues reported in #251. Then I started sift using `python -m uwsift` and loaded the file with `File` -> `Open File Wizard`, Reader `GOES-R ABI Level 1b`, `+ / Add files/dirs to list`, adding the mentioned file, then next.

For satpy I used:

```python
from satpy import Scene
sc = Scene(sensor="abi", filenames=["/media/nas/x21308/abi/ABI_CONUS_20190123/18/OR_ABI-L1b-RadC-M6C03_G16_s20191231841244_e20191231844017_c20191231844066.nc"])
sc.load(["C03"])
sc.save_dataset("C03", filename="/tmp/C03.tiff", overlay={"coast_dir": "/media/nas/x21308/shp", "color": "red"})
```

**Comment by djhoese** [comment]
Wow, thanks for the detailed bug report. If you pan/zoom around in SIFT does it correct itself? Are all the projections (see the drop down menu near the top) showing the wrong result?

I wonder if the longitude isn't being respected somewhere.

**Comment by djhoese** [comment]
Oh! What version of vispy do you have installed?

**Comment by djhoese** [comment]
Nevermind. I get the same thing on my system. Thanks again. I'll look in to it.

**Comment by gerritholl** [comment]
Adding as a comment here as it may be related — when I try to read the ABI L1B MESO 1 view, sift doesn't show any image at all.  Using the file (obtained from AWI S3):

`OR_ABI-L1b-RadM1-M3C03_G16_s20190231859245_e20190231859303_c20190231859347.nc`

upon loading it into sift, the following log messages appear (and nothing is shown):

```
ERROR 13:31:15 visuals:assess:L622 Could not determine viewable image area for '4131803e-ffb6-11e9-bc53-4c52620bf5ef'
INFO 13:31:15 document:animate_siblings_of_layer:L2473 no time siblings to chosen band, will try channel siblings to chosen time
INFO 13:31:15 document:animate_siblings_of_layer:L2476 No animation found
ERROR 13:31:20 visuals:assess:L622 Could not determine viewable image area for '4131803e-ffb6-11e9-bc53-4c52620bf5ef'
ERROR 13:31:20 visuals:assess:L622 Could not determine viewable image area for '4131803e-ffb6-11e9-bc53-4c52620bf5ef'
ERROR 13:31:20 visuals:assess:L622 Could not determine viewable image area for '4131803e-ffb6-11e9-bc53-4c52620bf5ef'
ERROR 13:31:21 visuals:assess:L622 Could not determine viewable image area for '4131803e-ffb6-11e9-bc53-4c52620bf5ef'
ERROR 13:31:21 visuals:assess:L622 Could not determine viewable image area for '4131803e-ffb6-11e9-bc53-4c52620bf5ef'
ERROR 13:31:26 visuals:assess:L622 Could not determine viewable image area for '4131803e-ffb6-11e9-bc53-4c52620bf5ef'
ERROR 13:31:26 visuals:assess:L622 Could not determine viewable image area for '4131803e-ffb6-11e9-bc53-4c52620bf5ef'
ERROR 13:31:27 visuals:assess:L622 Could not determine viewable image area for '4131803e-ffb6-11e9-bc53-4c52620bf5ef'
```

Again, satpy is doing fine:

![satpy visualisation for file mentioned above](https://user-images.githubusercontent.com/500246/68208395-5ae95680-ffd1-11e9-94a9-13842b795983.jpg)

**Comment by gerritholl** [comment]
Correction on the MESO view — it does show up, but in the wrong place (I was looking in an even wronger place which is why I initially thought it wasn't shown at all)

![sift_screenshot](https://user-images.githubusercontent.com/500246/68219448-4a8fa680-ffe6-11e9-9d88-265a11a4408b.png)

**Comment by djhoese** [comment]
I've spent some more time looking at this and I think this was broken in #234. This makes sense since a lot of the low-level geolocation functions were moved/modified in that PR. I tried running SIFT from the commit before that PR and it showed CONUS in the right spot. I need to walk through the changes to find where things got broken.

This is why we need more unit tests in SIFT.
