### ISSUE TITLE
`_pretty_identifiers` crash if `resolution` is a float

### ISSUE THREAD

**Issue by sjoro** [ssec/sift#265]
Some Satpy-readers have instrument `resolution` defined as a float. String formatting for:
`pretty_val = "{:d}m".format(value)` crashes as it is expecting an `int`.

**Comment by djhoese** [comment]
I think we could easily fix this, but in the long run SIFT needs to be "fixed" to handle 3D datasets (pressure_level, row, column). @sjoro what reader were you testing with? I'll have to make an issue in the future if it doesn't already exist about loading these level-based datasets as 3D arrays and providing a slider in the UI to choose what level you want to look at.

:man_facepalming: I just realized the "grib" reader isn't available by default in the current release.

**Comment by sjoro** [comment]
`seviri_l1b_native`, of course :)

**Comment by djhoese** [comment]
Oh man, I should not comment on GitHub in the morning. I assumed you were talking about pressure level, not resolution. I'll fix this as soon as possible. If it makes sense for you @sjoro I'm going to make it force the float to an integer. Right now we aren't dealing with sub-meter resolutions so I think we'll be OK.

**Comment by sjoro** [comment]
forcing floats to ints makes sense to me.
