### ISSUE TITLE
Satpy readers only version of SIFT

### ISSUE THREAD

**Issue by ColinDuff** [ssec/sift#3]
When opening products SATPY readers should be used. Satpy is well supported and and have a number of product readers so should be used to open files and have SIFT should have no independent product readers.

**Comment by ColinDuff** [comment]
Hi , i had already changed File Open to now use Satpy readers but what about your own data that you needed the File Open for - are these now all in Satpy

**Comment by djhoese** [comment]
The basic reading of data is probably implemented for each (really just ABI and AHI in L1B format) in SatPy, but may not produce all of the necessary metadata that SIFT would need. We would not want to remove File->Open until at least version 1.1 of SIFT.

**Comment by djhoese** [comment]
To provide an update on this issue: Satpy will be the only reader tool used in SIFT 1.1. The main issue I'm running in to now is deciding what Satpy readers should be enabled by default. There is currently no support for non-gridded data out of the box although that would be a nice future feature.

@ColinDuff @sjoro What readers do you need for the work you are doing? @gerritholl What readers are you interested in?

**Comment by gerritholl** [comment]
@djhoese I want use sift to play around using GOES-16 ABI CONUS data.

**Comment by sjoro** [comment]
@djhoese SEVIRI L1B and all L2, FCI L1B + L2, LI L2 as a starter.

**Comment by djhoese** [comment]
This is available in version 1.1 which I will release shortly...at least as a python package.
