### ISSUE TITLE
User configuration file would be useful

### ISSUE THREAD

**Issue by ColinDuff** [ssec/sift#6]
It would be useful to have a config file so that the user can have an environment suitable for their needs eg The list of available readers could be limited to eumetsat files only.

Also the screen display could be set for new/power users as mentioned in Issue #5

**Comment by djhoese** [comment]
This would work really well with the new configuration package I'm working on for SatPy that is based on dask's configuration module (and may be used by dask in the future). The command line could have a `--profile` to specify the path or name of the profile configuration to use. SIFT would need to have default locations to look for profile YAML files and would also have to have one that shows the previous state.

Another use case (I know there are a lot) would be default center point when loading the application and zoom level.

**Comment by djhoese** [comment]
Let's move any future discussion of this to #12. Closing this.
